services:
- type: web
  name: nocodb
  env: docker
  autoDeploy: false
  healthCheckPath: /dashboard#
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: nocodb-db
      property: connectionString
  - key: PORT
    value: 8080
  - key: NC_DISABLE_API_THROT
    value: "true"  # Optional: disable throttling

databases:
- name: nocodb-db
  databaseName: nocodb
  user: nocodb

